[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "dynamics"
authors = [{ name = "Antoine Groudiev", email = "antoine.groudiev@ens.psl.eu"}]
readme = "README.md"
description = "An experimental implementation of Rigid Body Dynamics algorithms."
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]
