[package]
name = "spatial"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { workspace = true }
numpy = { workspace = true}
pyo3 = { workspace = true }
rand = { workspace = true}
approx = { workspace = true }