[package]
name = "inertia"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
pyo3 = { workspace = true }
spatial = { workspace = true }